// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD00qs9ksJxsGGcj8HxymLrQo5iQQ-iw8E',
    appId: '1:922825618549:web:40e8d9ca5492f255def43c',
    messagingSenderId: '922825618549',
    projectId: 'with-ai-2f833',
    authDomain: 'with-ai-2f833.firebaseapp.com',
    storageBucket: 'with-ai-2f833.appspot.com',
    measurementId: 'G-1ZW099WVCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACnJqYoWc_wb-Kqqq2YD-ZaE3P0b-B2-A',
    appId: '1:922825618549:android:ac3ffa1864d9129fdef43c',
    messagingSenderId: '922825618549',
    projectId: 'with-ai-2f833',
    storageBucket: 'with-ai-2f833.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7xrVOFZdG9r-PSr9wdgO0tCQEjqcaFI',
    appId: '1:922825618549:ios:377e5bc9eff4a66adef43c',
    messagingSenderId: '922825618549',
    projectId: 'with-ai-2f833',
    storageBucket: 'with-ai-2f833.appspot.com',
    iosBundleId: 'com.example.withAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH7xrVOFZdG9r-PSr9wdgO0tCQEjqcaFI',
    appId: '1:922825618549:ios:377e5bc9eff4a66adef43c',
    messagingSenderId: '922825618549',
    projectId: 'with-ai-2f833',
    storageBucket: 'with-ai-2f833.appspot.com',
    iosBundleId: 'com.example.withAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD00qs9ksJxsGGcj8HxymLrQo5iQQ-iw8E',
    appId: '1:922825618549:web:aef7c75651fd2f0ddef43c',
    messagingSenderId: '922825618549',
    projectId: 'with-ai-2f833',
    authDomain: 'with-ai-2f833.firebaseapp.com',
    storageBucket: 'with-ai-2f833.appspot.com',
    measurementId: 'G-714YGWX37N',
  );
}
